## Tensor

In [38]:
import torch
import numpy as np

In [39]:
# Initalizing a Tensor

# Directly from data  
data = [[1, 2], [3, 4]]    
x_data = torch.tensor(data) 

# From a Numpy array 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# From another tensor
x_ones = torch.ones_like(x_data) # retain the properties of x_data(x_data의 속성 유지)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data(x_data의 속성을 덮어씀)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1768, 0.8248],
        [0.8036, 0.9434]]) 



In [40]:
# With random or constant values(random 또는 constant 값 사용하기)


shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2197, 0.4177, 0.4903],
        [0.5730, 0.1205, 0.1452]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [41]:
# Attributes of a Tensor(Attribute : 속성)

tensor = torch.rand(3, 4)

print(f"Shape if tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape if tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [42]:
# Operations on Tensor

# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [43]:
# Standard numpy-like indexing and slicing(NumPy식의 표준 인덱싱과 슬라이싱)

tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column: ', tensor[..., -1])
tensor[:, 1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [44]:
# joining tensor(텐서 합치기)

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [45]:
# Arithmetic operations(산술 연산)

# matrix multiplication     y1 = y2 = y3
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# element-wise product      z1 = z2 = z3
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [46]:
# Single-element tensors(단일-요소 텐서) 텐서의 all value를 하나로 aggregate하여 요소가 하나인 텐서의 경우
# item()을 사용하여 Python 숫자 값으로 변환할 수 있다

agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [47]:
# In-place operations(바꿔치기 연산) 연산 결과를 operand(피연산자)에 저장하는 연산, _접미사를 가진다
# ex: x.copy_(y) 나 x.t_() 는 x를 변경

print(tensor, "\n")
tensor.add_(5)
print(tensor)

# In-place operations는 메모리를 일부 절약하지만 history가 즉시 삭제되어 derivative(도함수) 계산에 문제가 발생할 가능성이 있다

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with NumPy      NumPy 변환 

In [48]:
# Tensor to NumPy array

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [49]:
# NumPy 배열의 변경 사항이 Tensor에 반영됨

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [51]:
# NumPy array to Tensor

n = np.ones(5)
t = torch.from_numpy(n)

In [52]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
