In [15]:
import tensorflow as tf

import numpy as np

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10 

X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()

print("Y(tensorflow): \n", Y_tf.numpy())

z = matmul(X, W) + B
Y_man_matmul = 1/(1 + exp(-z))

print("Y(with matmul):\n", Y_man_matmul.numpy())

Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
  x = X[x_idx]

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]

    z = tf.reduce_sum(x * w) + b
    a = 1/(1 +np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products): \n", Y_man_vec)

Y(tensorflow): 
 [[0.5732239  0.5207449  0.76788336]
 [0.7383052  0.774759   0.16945796]
 [0.29709536 0.24858807 0.43129715]
 [0.18789265 0.25561783 0.5795892 ]]
Y(with matmul):
 [[0.5732239  0.5207449  0.76788336]
 [0.7383053  0.774759   0.16945796]
 [0.2970954  0.24858806 0.43129715]
 [0.18789263 0.25561783 0.5795891 ]]
Y(with dot products): 
 [[0.57322387 0.52074493 0.76788329]
 [0.73830523 0.774759   0.16945797]
 [0.29709538 0.24858807 0.43129718]
 [0.18789264 0.25561782 0.57958916]]


In [16]:
n_neurons = [3, 5]

dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

A1 = dense1(X)
Y = dense2(A1)

W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()


print("X: {}\n".format(X.shape))

print("W1: ", W1.shape)
print("B1: ", B1.shape)

print("A1: {}\n".format(A1.shape))
print("W2 ", W2.shape)
print("B2, ", B2.shape)

print("Y: {}\n".format(Y.shape))

X: (4, 10)

W1:  (10, 3)
B1:  (3,)
A1: (4, 3)

W2  (3, 5)
B2,  (5,)
Y: (4, 5)



In [17]:
n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

dense_layers = list()
for n_neuron1 in n_neurons:
  dense = Dense(units=n_neuron1, activation='relu')
  dense_layers.append(dense)

print("Input: ", X.shape)
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  print("After dense layer ", dense_idx+1)
  print(X.shape, '\n')

Y = X

Input:  (4, 10)
After dense layer  1
(4, 10) 

After dense layer  2
(4, 20) 

After dense layer  3
(4, 30) 

After dense layer  4
(4, 40) 

After dense layer  5
(4, 50) 

After dense layer  6
(4, 60) 

After dense layer  7
(4, 70) 

After dense layer  8
(4, 80) 

After dense layer  9
(4, 90) 

After dense layer  10
(4, 100) 



In [18]:
X_cp = tf.identity(X)

n_neurons = [3, 4, 5]

dense_layers = list()

for n_neuron1 in n_neurons:
  dense = Dense(units=n_neuron1, activation='sigmoid')
  dense_layers.append(dense)

W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  w, b = dense.get_weights()

  W.append(w)
  B.append(b)

print("X(tensorflow): ", X.numpy())

for layer_idx in range(len(n_neurons)):
  w, b = W[layer_idx], B[layer_idx]

  X_cp = matmul(X_cp, w) + b
  X_cp = 1/(1 + exp(-X_cp))

print('Y(Maunal): \n', X_cp.numpy())

X(tensorflow):  [[0.56592125 0.4346844  0.44454247 0.3692835  0.57592016]
 [0.5659721  0.43453515 0.44427583 0.36930245 0.57620764]
 [0.5659476  0.4346351  0.4445148  0.36931664 0.57594556]
 [0.5659628  0.43455255 0.4442918  0.36929384 0.5761916 ]]
Y(Maunal): 
 [[0.56592125 0.4346844  0.44454244 0.3692835  0.57592016]
 [0.5659721  0.43453515 0.44427583 0.36930245 0.57620764]
 [0.5659476  0.43463507 0.4445148  0.36931664 0.57594556]
 [0.5659628  0.43455258 0.4442918  0.3692938  0.57619154]]


In [19]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

In [20]:
from tensorflow.keras.models import Model
class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=10, activation='sigmoid')
    self.dense2 = Dense(units=20, activation='sigmoid')

model = TestModel()
print(model.dense1)
print(model.dense2)

In [22]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model


X = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=10, activation='sigmoid')
    self.dense2 = Dense(units=20, activation='sigmoid')

  def call(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    return x

model1 = TestModel()
Y = model1(X)

In [23]:
import tensorflow as tf

import numpy as np

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10 

X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()

print("Y(tensorflow): \n", Y_tf.numpy())

z = matmul(X, W) + B
Y_man_matmul = 1/(1 + exp(-z))

print("Y(with matmul):\n", Y_man_matmul.numpy())

Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
    x = X[x_idx]

    for nu_idx in range(n_neuron):
      w, b = W[:, nu_idx], B[nu_idx]

      z = tf.reduce_sum(x * w) + b
      a = 1/(1 +np.exp(-z))
      Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products): \n", Y_man_vec)

Y(tensorflow): 
 [[0.41528746 0.45428637 0.12402209]
 [0.33733773 0.8440179  0.60001963]
 [0.1246224  0.08795512 0.95145446]
 [0.69169825 0.794712   0.05969982]]
Y(with matmul):
 [[0.4152875  0.45428634 0.12402209]
 [0.33733776 0.8440179  0.60001963]
 [0.12462239 0.08795513 0.9514545 ]
 [0.69169825 0.794712   0.05969981]]
Y(with dot products): 
 [[0.41528745 0.45428634 0.1240221 ]
 [0.33733774 0.84401791 0.60001961]
 [0.12462239 0.08795513 0.95145449]
 [0.6916983  0.79471197 0.0596998 ]]


In [24]:
model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

print(type(model.trainable_variables))
print(len(model.trainable_variables))

for train_var in model.trainable_variables:
  print(train_var.shape)

<class 'list'>
4
(10, 10)
(10,)
(10, 20)
(20,)
