# Conv_layers

In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 5
n_filter = 10
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                          shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

output = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape, B.shape)
print(output.shape)

(32, 28, 28, 5)
(3, 3, 5, 10) (10,)
(32, 26, 26, 10)


In [5]:
import numpy as np

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                          shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

output = conv(images)
print("Output(Tensorflow): \n", output.numpy().squeeze())
W, B = conv.get_weights()


images = images.numpy().squeeze()
W = W.squeeze()
#print(images.shape)
#print(W.shape)
#print(B.shape)

output_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))

for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
    window = images[i : i+k_size, j : j+k_size : ]
    output_man[i, j] = np.sum(window*W) + B


print("Output(Manual): \n", output_man)

Output(Tensorflow): 
 [[ 0.57070434  0.30159354  0.5343246 ]
 [ 0.2468829  -0.02323267  0.2600533 ]
 [-0.44060054 -0.39378458 -0.10270729]]
Output(Manual): 
 [[ 0.57070434  0.3015936   0.53432471]
 [ 0.246883   -0.02323264  0.26005325]
 [-0.44060057 -0.39378455 -0.10270725]]


# Conv_layers_with_filters

# 

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 3
n_filter = 5
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

Y = conv(images)

W, B = conv.get_weights()

print("Input Images: {}\n".format(images.shape))
print("W/B: {} / {}".format(W.shape, B.shape))
print("Output Image: {}".format(Y.shape))

Input Images: (32, 28, 28, 3)

W/B: (3, 3, 3, 5) / (5,)
Output Image: (32, 26, 26, 5)


In [2]:
import numpy as np

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))


# Forward Propagation(Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size, activation='sigmoid')
Y = conv(images)

Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print("Output(Tensorflow): \n", Y)

W, B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
  c_W = W[:, :, :, c]
  c_b = B[c]

  for h in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
      window = images[h:h+k_size, j:j+k_size, :]
      conv = np.sum(window*c_W) + c_b
      conv = 1/(1 + np.exp(-conv))

      Y_man[h, j, c] = conv

print("Output(Manual): \n", np.transpose(Y_man, (2, 0, 1)))

Output(Tensorflow): 
 [[[0.39925215 0.32592776]
  [0.34264806 0.45000565]]

 [[0.4209333  0.3975372 ]
  [0.49071375 0.44948056]]

 [[0.5758597  0.28393266]
  [0.42131698 0.47559834]]]
Output(Manual): 
 [[[0.39925216 0.32592776]
  [0.34264807 0.45000568]]

 [[0.4209333  0.39753723]
  [0.49071379 0.44948058]]

 [[0.57585977 0.28393264]
  [0.42131695 0.47559835]]]
