In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1))
pool_max = MaxPooling1D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print("x :{}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape, 
                                              pooled_max.numpy().flatten()))

x = x.numpy().flatten()
pooled_max_man = np.zeros((L - f + 1, ))
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_max_man[i] = np.max(window)

print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape, 
                                              pooled_max_man))

x :(1, 10, 1)
[ 0.15644617  0.2033005   0.43847024  0.81104547  1.9017991  -1.0501548
  0.2210595  -1.6561192  -1.0344648   0.28828952]
pooled_max(Tensorflow): (1, 9, 1)
[ 0.2033005   0.43847024  0.81104547  1.9017991   1.9017991   0.2210595
  0.2210595  -1.0344648   0.28828952]
pooled_max(Manual): (9,)
[ 0.20330051  0.43847024  0.81104547  1.90179908  1.90179908  0.2210595
  0.2210595  -1.03446484  0.28828952]


In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import AveragePooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1))
pool_avg = AveragePooling1D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x :{}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape, 
                                              pooled_avg.numpy().flatten()))

x = x.numpy().flatten()
pooled_avg_man = np.zeros((L - f + 1, ))
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_avg_man[i] = np.mean(window)

print("pooled_max(Manual): {}\n{}".format(pooled_avg_man.shape, 
                                              pooled_avg_man))

x :(1, 10, 1)
[ 0.24277362 -0.65716034  0.9227822   1.0110965  -0.42311326 -0.62663925
  0.1871835  -0.53219765 -0.12248148 -0.37612364]
pooled_avg(Tensorflow): (1, 9, 1)
[-0.20719336  0.13281092  0.96693933  0.29399163 -0.52487624 -0.21972787
 -0.17250708 -0.32733956 -0.24930257]
pooled_max(Manual): (9,)
[-0.20719336  0.13281092  0.96693933  0.29399163 -0.52487624 -0.21972787
 -0.17250708 -0.32733956 -0.24930257]


In [3]:
from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print("x :{}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape, 
                                              pooled_max.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f + 1):
  for j in range(n_W - f + 1):
    window = x[i:i+f, j:j+f]
    pooled_max_man[i, j] = np.max(window) 

print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape, 
                                              pooled_max_man))

x :(1, 5, 5, 1)
[[-0.4340362   0.28547525  0.7681131   0.32134083  0.8452097 ]
 [-2.2013807  -1.6502237  -0.42466694 -1.5200467   0.01418578]
 [ 0.1884323   0.04774365  0.41820225 -2.7725444  -0.2641222 ]
 [ 1.8908267  -1.3054084   0.6662803   0.57421976  0.38393277]
 [ 0.2533798   0.17741673  0.3675127   1.6019856  -0.2657823 ]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[0.28547525 0.7681131  0.7681131  0.8452097 ]
 [0.1884323  0.41820225 0.41820225 0.01418578]
 [1.8908267  0.6662803  0.6662803  0.57421976]
 [1.8908267  0.6662803  1.6019856  1.6019856 ]]
pooled_max(Manual): (4, 4)
[[0.28547525 0.76811308 0.76811308 0.84520972]
 [0.18843231 0.41820225 0.41820225 0.01418578]
 [1.8908267  0.66628033 0.66628033 0.57421976]
 [1.8908267  0.66628033 1.60198557 1.60198557]]


In [4]:
from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x :{}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape, 
                                              pooled_avg.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f + 1):
  for j in range(n_W - f + 1):
    window = x[i:i+f, j:j+f]
    pooled_avg_man[i, j] = np.mean(window) 

print("pooled_avg(Manual): {}\n{}".format(pooled_avg_man.shape, 
                                              pooled_avg_man))

x :(1, 5, 5, 1)
[[-0.09088124 -0.93709964 -0.4911867  -0.77233803 -1.4605644 ]
 [ 1.0161346   0.31953505  1.2059529   0.6629455  -1.7726578 ]
 [ 0.5466794  -0.5783455   0.3443904   0.33411863 -0.10285926]
 [ 1.3674948  -0.5924833   2.549064   -0.6296322   1.0127579 ]
 [-0.7385894  -0.31821856  1.9485828   1.5998152   0.2757234 ]]
pooled_avg(Tensorflow): (1, 4, 4, 1)
[[ 0.07692219  0.0243004   0.1513434  -0.83565366]
 [ 0.32600087  0.3228832   0.63685185 -0.21961322]
 [ 0.18583637  0.43065637  0.6494852   0.15359628]
 [-0.07044911  0.8967362   1.3669574   0.5646661 ]]
pooled_avg(Manual): (4, 4)
[[ 0.07692219  0.0243004   0.15134341 -0.83565366]
 [ 0.32600087  0.32288319  0.63685185 -0.21961322]
 [ 0.18583637  0.43065637  0.64948517  0.15359628]
 [-0.07044911  0.8967362   1.36695743  0.56466609]]
