In [1]:
import math
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 3
f, s = 2, 2

x = tf.random.normal(shape=(N, n_H, n_W, n_C))

pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

pooled_max_t = np.transpose(pooled_max.numpy().squeeze(), (2, 0, 1))
print('pooled_max(tensorflow): {}\n{}'.format(pooled_max.shape, 
                                              pooled_max_t))


x = x.numpy().squeeze()
(n_H - f)/s + 1
n_H_ = math.floor((n_H - f)/s + 1)
n_W_ = math.floor((n_W - f)/s + 1)
pooled_max_man = np.zeros(shape=(n_H_, n_W_, n_C))

for c in range(n_C):
  c_image = x[:, :, c]

  h_ = 0
  for h in range(0, n_H - f + 1, s):
    w_ = 0
    for w in range(0, n_W - f + 1, s):
      window = c_image[h:h+f, w:w+f]
      pooled_max_man[h_, w_, c] = np.max(window)

      w_ += 1
    h_ += 1


pooled_max_t = np.transpose(pooled_max_man.squeeze(), (2, 0, 1))
print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape,
                                          pooled_max_t))

pooled_max(tensorflow): (1, 2, 2, 3)
[[[ 1.912522   -0.26688984]
  [ 0.35166627  0.27987194]]

 [[-0.23428167  0.93804544]
  [ 0.45764503  1.2300134 ]]

 [[ 0.5363828   0.09210803]
  [ 0.11198822  0.23297155]]]
pooled_max(Manual): (2, 2, 3)
[[[ 1.91252196 -0.26688984]
  [ 0.35166627  0.27987194]]

 [[-0.23428167  0.93804544]
  [ 0.45764503  1.23001337]]

 [[ 0.53638279  0.09210803]
  [ 0.11198822  0.23297155]]]


In [3]:
from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape=(1, 28, 28, 3))
images_ = np.transpose(images.numpy().squeeze(), (2, 0, 1))
# print(images_)
print(images.shape)

zero_padding = ZeroPadding2D(padding=2)
y = zero_padding(images)

print(y.shape)
# print( np.transpose(y.numpy().squeeze(), (2, 0, 1)))

(1, 28, 28, 3)
(1, 32, 32, 3)


In [4]:
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))
conv = Conv2D(filters=1, kernel_size=3, padding='same')
y = conv(images)
print(images.shape)

(1, 28, 28, 3)


In [5]:
from tensorflow.keras.layers import MaxPooling2D

images = tf.random.normal(shape=(1, 28, 28, 3))
pool = MaxPooling2D(pool_size=3, strides=2)
y = pool(images)

print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 3)
